version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    networks:
      - gradely-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - gradely-net

networks:
  gradely-net:
    driver: bridge

